### ISSUE TITLE
DbusMethodCall: positional or keyword arguments?

### ISSUE THREAD

**Issue by fohrloop** [fohrloop/wakepy#134]
The current implementation of `DbusMethodCall` looks like this:

```python
@dataclass
class DbusMethodCall(Call):
    method: DbusMethod
    args: dict[str, Any] | Tuple[Any, ...] | List[Any]
```
in other words, it accepts the arguments (`args`) for the method as `dict`, `tuple` or `list`. The tuple and list options are currently supported by the `JeepneyDbusAdapter`. The `dict` option does not work, but crashes:

```
    def serialise(self, data, pos, endianness, fds=None):
        if not isinstance(data, tuple):
>           raise TypeError("Expected tuple, not {!r}".format(data))
E           TypeError: Expected tuple, not {'app_id': 'wakepy', 'toplevel_xid': 42, 'reason': 'wakelock active', 'flags': <GnomeFlag.INHIBIT_SUSPEND: 4>}

venv/lib/python3.10/site-packages/jeepney/low_level.py:199: TypeError
````

The crash is expected as there is no yet support for dict type of arguments for Dbus method calls. 

### Tasks

- [x] Consider, if the dict type of arguments should be supported, and if, how?
- [x] Make DbusMethodCall.args to be always a tuple
    - Keep the `args` parameter of DbusMethodCall.\_\_init\_\_  as tuple, list or dict
 - [x] Add validation for `args` parameter of the \_\_init\_\_ call.
     - Should validate that these match with the `call.method.params` (if there are any). Do not accept dictionaries if the `call.method.params` is None.
 - [x] Add .get_kwargs() or .kwargs to DbusMethodCall which will retrieve the `args` as *dictionary* if possible. If not possible, return None or raise some type of exception.

**Comment by fohrloop** [comment]
The JeepneyDbusAdapter process method implementation looks roughly like this:

```python

class JeepneyDbusAdapter(DbusAdapter):

    def process(self, call: DbusMethodCall):
        addr = DBusAddress(
            object_path=call.method.path,
            bus_name=call.method.service,
            interface=call.method.interface,
        )

        msg = new_method_call(
            addr,
            method=call.method.name,
            signature=call.method.signature,
            body=call.args,
        )

        connection = open_dbus_connection(bus=call.method.bus)
        reply = connection.send_and_get_reply(msg, timeout=self.timeout)
        resp = unwrap_msg(reply)
        return resp
```

The process() gets a `DbusMethodCall` object (call) and creates a `jeepney.low_level.Message` instance (msg). The `new_method_call` only accepts positional arguments (the `body` parameter).  

One option here would be to convert the `call.args` (which can now be dict, tuple or list) to a tuple inside the `JeepneyDbusAdapter.process`, since we have the available information there:

```python
>> call.method.params
('app_id', 'toplevel_xid', 'reason', 'flags')
>>> call.args
{'app_id': 'wakepy',
 'toplevel_xid': 42,
 'reason': 'wakelock active',
 'flags': <GnomeFlag.INHIBIT_SUSPEND: 4>}
```

But if that would be done in the DbusAdapter subclass, then every subclass should do that. It would be more convenient if that logic was in the `DbusMethodCall` class. In addition, there could be some logic which asserts that the call parameter names (`call.method.params`) are same as the keys in the `args` if that is a dictionary. Perhaps even types could be checked or coerced? (at least for simple types like int, float and string?). 

The DbusMethodCall could still be initialized with `args` being positional (tuple/list) or keywords (dict). The *attribute* DbusMethodCall.args could always be tuple. And in addition, there could be `.get_kwargs()` or `.kwargs` which would return the kwargs if the parameter names are given (the DbusMethod.params is optional).
