### ISSUE TITLE
Linux: keep.presenting & keep.running with org.gnome.SessionManager (D-Bus)

### ISSUE THREAD

**Issue by fohrloop** [fohrloop/wakepy#136]
This is a new method I've been using in the v.0.8.0 for testing. Now that many things are ready, it would be a good time to finalize the code under `keep.running()` and `keep.presenting()` and make the org.gnome.SessionManager based method work.

### Tasks

- [x] Add a general (not org.gnome.SessionManager specific) tests for keep.running and keep.presenting which should pass. Idea is to test that the context manager and the underlying machinery works end-to-end. ([PR 137](https://github.com/fohrloop/wakepy/pull/137))
- [x] Check that the org.gnome.SessionManager based methods work (manually) ([PR 138](https://github.com/fohrloop/wakepy/pull/138))
- [x] Add documentation for the org.gnome.SessionManager based methods. ([PR 139](https://github.com/fohrloop/wakepy/pull/139))
