### ISSUE TITLE
Tests failing on main - Fedora 40 Python 3.12.5

### ISSUE THREAD

**Issue by fohrloop** [fohrloop/wakepy#380]
Just tried running tests on latest commit on `main` (6b3b0f89199ee47fa0cf0e1ca1a3586c47d43558), and here's what I get:

<details>
<summary>
inv test
</summary>

```
❯ inv test output
Running:  env -u DBUS_SESSION_BUS_ADDRESS python -m pytest -W error --cov-branch --cov ./src --cov-fail-under=100 
ImportError while loading conftest '/home/fohrloop/code/wakepy/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from tests.unit.test_core.testmethods import TestMethod
tests/unit/test_core/testmethods.py:41: in <module>
    from wakepy.core import PlatformType
src/wakepy/__init__.py:9: in <module>
    from . import methods as methods
src/wakepy/methods/__init__.py:29: in <module>
    from . import _testing as _testing
src/wakepy/methods/_testing.py:5: in <module>
    from wakepy.core import Method, PlatformType
src/wakepy/core/__init__.py:17: in <module>
    from .method import Method as Method
E     File "/home/fohrloop/code/wakepy/src/wakepy/core/method.py", line 73
E       """Lists the platforms the Method supports. If the current platform is not
E       ^^^
E   SyntaxError: invalid escape sequence '\*'
Running:  coverage html && python -m webbrowser -t htmlcov/index.html 
No data to report.
```

</details>

if the `SyntaxError: invalid escape sequence '\*'` above is fixed, there's a set of tests which still fail:

<details>
<summary>
inv tests still failing
</summary>

```
FAILED tests/integration/test_dbus_adapters.py::TestJeepneyCalculatorService::test_wrong_signature - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.socket fd=-1, family=1, type=1, proto=0>
FAILED tests/integration/test_dbus_adapters.py::TestJeepneyDbusAdapter::test_close_connections - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.socket fd=-1, family=1, type=1, proto=0>
ERROR tests/integration/test_dbus_adapters.py::TestJeepneyDbusAdapter::test_adapter_caching - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.socket fd=-1, family=1, type=1, proto=0>
```
</details>

The strange thing is that the commit, which was from #379 , had normal CI pipelines checks which [all passed](https://github.com/fohrloop/wakepy/actions/runs/10854897920/job/30126336172?pr=379).

### Tasks
- [x] Find out why the tests are failing locally, but not in the pipelines. 
- [x] Make the pipelines fail if there are Warnings
- [x] ~If possible, make the pipelines fail with the sockets related PytestUnraisableExceptionWarnings~ Not feasible/possible. Added a test for the warnings filter regex that makes sure the Ubuntu and Fedora 40 versions are handled.
- [x] Fix the SyntaxWarning
- [x] Fix the PytestUnraisableExceptionWarning

**Comment by fohrloop** [comment]
#### Debugging information
Running `python -m pytest` does not reproduce the error

<details>
<summary>
python -m pytest output
</summary>

```
(venv) fohrloop@niko-fedora:~/code/wakepy$ python -m pytest
==================================================================== test session starts ====================================================================
platform linux -- Python 3.12.5, pytest-8.1.1, pluggy-1.5.0
rootdir: /home/fohrloop/code/wakepy
configfile: pyproject.toml
plugins: cov-4.1.0, time-machine-2.14.0
collected 279 items / 1 skipped                                                                                                                             

tests/integration/test_dbus_adapters.py ...........                                                                                                   [  3%]
tests/unit/test__init__.py ....                                                                                                                       [  5%]
tests/unit/test_core/test_activationresult.py ......................                                                                                  [ 13%]
tests/unit/test_core/test_calls.py ...............                                                                                                    [ 18%]
tests/unit/test_core/test_constants.py ...                                                                                                            [ 19%]
tests/unit/test_core/test_dbus.py .......                                                                                                             [ 22%]
tests/unit/test_core/test_heartbeat.py .                                                                                                              [ 22%]
tests/unit/test_core/test_method/test_activation.py ..................................                                                                [ 34%]
tests/unit/test_core/test_method/test_method.py ........                                                                                              [ 37%]
tests/unit/test_core/test_mode.py ......................................................                                                              [ 56%]
tests/unit/test_core/test_platform.py .........                                                                                                       [ 60%]
tests/unit/test_core/test_prioritization.py ..............................                                                                            [ 70%]
tests/unit/test_core/test_registry.py .....                                                                                                           [ 72%]
tests/unit/test_core/test_strenum.py ......                                                                                                           [ 74%]
tests/unit/test_main.py ................                                                                                                              [ 80%]
tests/unit/test_methods/test_freedesktop.py ......................                                                                                    [ 88%]
tests/unit/test_methods/test_gnome.py ........                                                                                                        [ 91%]
tests/unit/test_methods/test_macos.py ....                                                                                                            [ 92%]
tests/unit/test_modes.py ....................                                                                                                         [100%]

============================================================== 279 passed, 1 skipped in 2.11s ===============================================================
```

</details>
