### ISSUE TITLE
Split responsibilities to Mode, Method, activate() and activate_using() (v. 0.8.0)

### ISSUE THREAD

**Issue by fohrloop** [fohrloop/wakepy#69]
This is basically a ticket to myself, and is continuation of work in the [PR #51](https://github.com/fohrloop/wakepy/pull/51), which left the main branch in an unfinished and bit messy state. 

#### Modes
- [x] Clean up code for Mode. The purpose of Mode is to simply provide the main API and context manager for the user. Everything else should be handled elsewhere. (PR [#70](https://github.com/fohrloop/wakepy/pull/70))
- [x] Remove creation of DBusAdapter instances from Modes. Pass the DBusAdapter class to a ModeActivationManager -> ModeActivator -> Caller and create an instance of the adapter there (in separate thread)   (PR [#70](https://github.com/fohrloop/wakepy/pull/70))
- [x] Remove prioritization of methods from Modes. Prioritization should be done in ModeActivator.  (PR [#70](https://github.com/fohrloop/wakepy/pull/70))
- [x] Implement `Mode.__exit__` and add `ModeExit` exception which can be used to exit the mode with statement block.  (PR [#72](https://github.com/fohrloop/wakepy/pull/72))
- [x] The callables for Modes like keep.running and keep.presenting should be functions which return instances of Modes. Calling keep.running() should call return a fresh instance of `Mode` (for supporting running wakepy in multiple threads) (PR [#71](https://github.com/fohrloop/wakepy/pull/71))
- [x] Create tests for Mode  (PR [#71](https://github.com/fohrloop/wakepy/pull/71))

#### Deprecated
*work done on this ticket but not relevant anymore*
- [x] Create a ModeActivationManager class. (PR [#76](https://github.com/fohrloop/wakepy/pull/76))
using the queues.

**Comment by fohrloop** [comment]
I wrote some initial ideas in https://github.com/fohrloop/wakepy/issues/75 about renaming ModeActivator to ModeActivationProcess and splitting the responsibilities in three: MethodSelector, MethodPrioritizer and ModeActivator.

I could try to implement the classes next. Modifying the list above to reflect the changes.

**Comment by fohrloop** [comment]
As mentioned in https://github.com/fohrloop/wakepy/discussions/100, wakepy Mode activation process will be a blocking operation. This makes it possible to do everything, except heartbeat, in the main thread, which in turn makes things a lot easier. I've already written some documentation to the 0.8.0dev ("main") docs about how this all will work. The plan is roughly:
- Have Mode class as the context manager
- Have activate(methods, ...) function which can activate a "mode" (list of method classes)
- Have activate_using(method, ...) function which may activate a "mode" using a single Method. 
- Have Method class for sole purpose of defining subclasses Method
- Have a Heartbeat class which runs a heartbeat in separate thread.

Rough implementation of activate():

```python
def activate(methods: list[MethodCls], ...) -> tuple[ActivationResult, HeartBeat|None]:
    prioritized_methods = prioritize_methods(methods)
    result = ActivationResult()

    for method in prioritized_methods:
        methodresult, heartbeat = activate_using(method, ...)
        result.add(methodresult)
        if result.success:
            break
    return result, heartbeat
```
- The idea behind activate() function is that you don't need to have Mode instance in order to activate a "mode" defined by a list of Methods.

Rough implementation of activate_using() (pseudocode):

```python
def activate_using(methodcls: MethodCls, ...):
    method = methodcls()
    if check_platform_support(method) is False:
         return MethodUsageResult(failure_stage=PLATFORM_SUPPORT), None
    if check_requirements(method) is False:
        return MethodUsageResult(failure_stage=REQUIREMENTS), None
    entered = try_enter_mode(method)
    heartbeat_started = try_heartbeat(method)
    if not entered or not heartbeat_started:
        return MethodUsageResult(failure_stage=ACTIVATION), None
    if heartbeat_started:
        heartbeat = Heartbeat(method)
        heartbeat.start()
    return MethodUsageResult(), heartbeat

**Comment by fohrloop** [comment]
The rest of the work on this ticket has been split into multiple tickets. This one is done and can be closed.
