### ISSUE TITLE
Prioritization and selecting used Methods

### ISSUE THREAD

**Issue by fohrloop** [fohrloop/wakepy#75]
Think about how prioritization and selecting used Methods should work. What kind of API there should be?  Would using list of strings be good, or should user need to use list of Method classes? 

### Tasks:
- [x] Think about how prioritization and selecting used Methods should work --  (below)
- [x] methods_priority dictionary for setting priority  (PRs [#90](https://github.com/fohrloop/wakepy/pull/90), [#91](https://github.com/fohrloop/wakepy/pull/91),  [#97](https://github.com/fohrloop/wakepy/pull/97))
- [x] Possibility of getting methods based on mode (PR [#88](https://github.com/fohrloop/wakepy/pull/88))
- [x] Possibility of selecting modes with "skip" and "use_only" (PR [#89](https://github.com/fohrloop/wakepy/pull/89))
- [x] Add support for selecting and prioritizing methods to keep.running and keep.presenting  (PR [#97](https://github.com/fohrloop/wakepy/pull/97))

### Detailed plan

_This is detailed summary from all the messages from below. Will be updating this to reflect the latest view of how this is going to be implemented; no need to read all the messages below as much of it is obsolete and not relevant._

#### In the main thread
* The API looks something like this (assuming keep.running has methods called A, B, C, D, E, F and G):

```python
mode = keep.running(
    dont_use=['G'], priority_order = [{'A', 'B'}, '*', {'E', 'F'}]
)
```

* The implementation looks something like this

```python
def running(only_use:list[str], dont_use:list[str], priority_order:list[str|set[str]]) -> Mode:
    methods_for_mode = get_methods_for_mode(ModeName.KEEP_RUNNING)
    selected_methods = select_methods(methods_for_mode, only_use=only_use, dont_use=dont_use)
    return Mode(methods=selected_methods, priority_order=priority_order)
```

* In `Mode.__init__`, check the priority order against the selected methods. ([PR #91](https://github.com/fohrloop/wakepy/pull/91))

#### In the activation thread
* Get a list of prioritized methods. 

```python
# methods: List[MethodCls]
# priority_order: List[str | Set[str]]
prioritized_methods: List[MethodCls] = get_prioritized_methods(methods, priority_order)
```

* When resolving priority, 
(1) prioritize using the priority_order (PR [#94](https://github.com/fohrloop/wakepy/pull/94)) and 
(2) prioritize within each set automatically (PR [#96](https://github.com/fohrloop/wakepy/pull/96))  and 
(3) form a flat list (PR [#96](https://github.com/fohrloop/wakepy/pull/96)) ;

```python

# let's say we have
priority_order = [{'A', 'B'}, '*', {'E', 'F'}]
methods = [A, B, C, D, E, F]

# (1) could make this
methods = [{A, B}, {C, D}, {E, F}]

# (2) could make this
methods = [[B, A], [C, D], [F, E]]

# (3) could make this
methods = [B, A, C, D, F, E]
```

* Then, follow the normal mode activation process; in priority order, try to activate the mode using the prioritized methods.

**Comment by fohrloop** [comment]
I've been thinking a bit about the possible prioritization and selection or blacklisting methods. I think that could be done like this:

Instead of running single "ModeActivator" in the worker thread, rename it to "ModeActivationProcess" and split the resposibilities to:
### 1) MethodSelector
- First, use platform support information for automatic selection of methods. Each method has `supported_platforms` attribute for this.
- Then, user-defined filtering / selection from this list, using a "whitelist" or a "blacklist"
### 2) MethodPrioritizer
- First, use some automatic prioritization logic. There is no such thing yet, but something could be done automatically.
- Then, use user-defined priority args (lower_priority and higher_priority) to set some methods to higher priority than others.
### 3) ModeActivator
- This loops over all the methods in the prioritized list and (1) checks requirements (2) tries to activate the mode using the method.

### Details: Automatic prioritization
- Could check some environment variables: Are they set or not? Perhaps give some priority based on the values?
- There could be `Method.get_priority_boost` which could give a prioritization number, for example (TINY:1, SMALL: 2, MEDIUM: 3, LARGE: 4 and HUGE: 5). 
- This is just some optimization and I'm not sure if it's needed or not. 
- Support could be added in a later version, if needed.

### Details: Possible API

Could be something like
```python
mode = keep.running(
    methods=dict(use_only=[A, B, C, D, E], lower_priority=[C], higher_priority=[B, A])
)
```
which could select from `[A, B, C, D, E, F, G, H, I]` the `[A, B, C, D, E]` and then prioritize this first using the automatic prioritization, and then user-defined prioritization. The final output could be `[B, A, D, E, C]` or   `[B, A, E, D, C]`, depending on the automatic prioritization (D vs E). The methods are strings. If `lower_priority` or `higher_priority` is a list, that order is used. If that is a set, these are prioritized higher (or lower) in the automatic prioritization order.

For blacklisting methods, the keyword could be `skip`, like this:

```python
# Could give prioritized list: [B, A, E, C] from [A, B, C, D, E]
mode = keep.running(
    methods=dict(skip=[D], lower_priority=[C], higher_priority=[B, A])
)
```

The keywords could be also `whitelist` and `blacklist` instead of `use_only` and `skip`.

## Implications
### 1) Simple things are simple
This is the most important. The API is kept really simple, as anyone wanting to just use wakepy out of the box gets the methods filtered by platform support and possibly automatically prioritized with simple:
```python
with keep.running() as k:
    ...
```
### 2) Full control to power users
This is the second important point: Complicated things are possible. It could be possible to even drill down to controlling something platform-specific by using some logic for creating the `methods` kwargs:

```python
from wakepy import CURRENT_PLATFORM, PlatformName, keep

if CURRENT_PLATFORM == PlatformName.LINUX:
    methods = dict(skip=[D], lower_priority=[C], higher_priority={B, A})
else:
    methods = dict(higher_priority={B, A})

mode = keep.running(methods=methods)

with mode as m:
    ...
```
- This would always skip D on linux (In case D would be supported on linux and some other platform, and only wanting to disable this in linux)
- This would prioritize A and B to be the first, but in the order which is automatically determined (as given an unordered set, not a list)

**Comment by fohrloop** [comment]
Thinking about how to pass around the methods and the new method selection and prioritization related arguments. The current implementation has something like this:

```python
def running():
    return Mode(methods=running_methods)
```

Where `running_methods` is a hard-coded list of methods which implement the "keep.running" mode. Now if we look at the new API idea from above, it could be that in the future the mode is initialized with

```python
mode = keep.running(
    methods=dict(skip=[D], lower_priority=[C], higher_priority=[B, A])
)
```

where A, B, C and D are strings. These strings can be pretty easily converted to Method classes. 

### Single keyword argument "methods" for keep.running ?

The keyword argument `methods` for keep.running probably makes sense to the user. It could of course be also 

 ```python
mode = keep.running(
    skip_methods=[D], lower_priority_methods=[C], higher_priority_methods=[B, A]
)
```

or even

 ```python
mode = keep.running(
    skip=[D], lower_priority=[C], higher_priority=[B, A]
)
```

although I like that the number of arguments in `keep.running` (and other mode creators) is kept smaller if everything: skip, use_only, lower_priority and higher_priority are grouped into one argument: methods. This is also a power-user option and typical users would not have to think about this, and having option looks neater than having four. So, I'm inclined to having just a single argument for the method selection and prioritization options. 

### Argument methods for Mode.__init__

I think the Mode(methods=all_methods_that_mode_may_use) makes sense. In this context, `methods` describes all the methods that can be used to enter a Mode. 

### How to pass the custom selection and prioritization logic to Modes?

We can't obviously pass the `methods` from

```python
mode = keep.running(
    methods=dict(skip=[D], lower_priority=[C], higher_priority=[B, A])
)
```
 
as methods to Mode as that keyword argument name is already in use. 

#### MethodCurator

Perhaps at this point the user-given arguments should be used to create some MethodCurator object which can select and prioritize methods? This could also translate the method names (strings) into Method classes. So, something like this:

```python
def running(methods: dict[str, list[str] | set[str]):
    method_curator = MethodCurator(**methods)
    return Mode(methods=running_methods, method_curator=method_curator)
```

The MethodCurator would then have 

```python
method_curator.skip: list[MethodCls] | None
method_curator.use_only: list[MethodCls] | None
method_curator.lower_priority: list[MethodCls] | set[MethodCls]
method_curator.higher_priority: list[MethodCls] | set[MethodCls]
```
where `MethodCls = Type[Method]`. Only one of `skip` and `use_only` could be not None. This could also have methods like

```python
selected_methods = method_curator.select_from(methods)
prioritized_methods = method_curator.prioritize(selected_methods)
```

In reality, if we had automatic selection and prioritization, this should be combined:


```python
supported_methods, unsupported_methods = MethodSelector().split_by_platform_support(methods)
selected_methods = method_curator.select_from(supported_methods)

automatically_prioritized = MethodPrioritizer().prioritize(selected_methods)
prioritized_methods = method_curator.prioritize(automatically_prioritized)
```

**Comment by fohrloop** [comment]
It might be even nicer actually if the `methods` argument of the `running` was already a `MethodCurator` object, not a dictionary. This makes it easier to explain the args and also much easier for writing the type annotations. So, perhaps:

```python
def running(method_curator: MethodCurator):
    return Mode(methods=running_methods, method_curator=method_curator)
```

which would make the API usage look like this:

```python
mode =  keep.running(
    method_curator=MethodCurator(skip=[D], lower_priority=[C], higher_priority=[B, A])
)

with mode as m:
    ...
```

**Comment by fohrloop** [comment]
Decided to make a MethodCurationOpts class instead of a MethodCurator class. The MethodCurationOpts is simple dataclass which converts the input arguments from method names to method classes, and provides some basic validation to the arguments. It can be used to move the method selection and prioritization options around. The methods planned for MethodCurator can probably be simple functions.

**Comment by fohrloop** [comment]
Next, need to implement something like this:

```python
selected_methods = select_methods(methods, skip, use_only)
supported_methods = [m for m in selected_methods if platform m.supported_platforms]
prioritized_methods = prioritize_methods(supported_methods, lower_priority, higher_priority)

unsupported_methods = [m for m in selected_methods if platform not in m.supported_platforms]
```

**Comment by fohrloop** [comment]
I'm not sure if I'm happy with the solution yet. Here are some of my thoughts:

### lower_priority and higher_priority -> priority_order ?
The `lower_priority` and `higher_priority` arguments are clear, but they do not cover all the possible use cases even with `use_only` and `skip`. For example, if a Mode has 6 methods: A, B, C, D, E, F, and `higher_priority = (A, B)` and `lower_priority = (E, F)`, there is no possibility for the user to say anything about the ordering in the "middle priority"; should it be [C, D] or [D, C] ? Users are forced put any method of which order they want to control to "low" or "high priority. That does not fell right.

This could be solved quite simply with a *single* argument, say, `priority_order`, which would be a list of strings, like [A, B, C, D, E, F]. Asterisk (`*`) could be used to denote "any other selected methods", so the previous example could be [A, B, '\*', E, F]. If user would like to divide methods to different priority levels, but would not want to order the methods within the level, a set can be used, like this: [{A, B}, '*', {E, F}]. The number of different priority levels is then practically unlimited. Simply defining `priority_order = [A, B]` would mean that use method A and then method B and then *any other selected methods* (implicit asterisk at the end). This is basically same as defining only `higher_priority`. Defining `priority_order = ['*', E, F]` would mean: "use any selected methods first, and then E and then F", which is the same as defining only `lower_priority`.

### Select methods at the start?

The previous suggestion was to select methods in the worker/activation thread. However, it could be probably simpler to select the methods right at the start, so something like:

```python
def running(methods:dict) -> Mode:
    methods_for_mode = get_methods_for_mode(ModeName.KEEP_RUNNING)
    selected_methods = select_methods(methods_for_mode, skip=methods.get('skip'), only_use=methods.get('only_use')
    return Mode(methods=selected_methods, priority_order=methods.get('priority_order'))
```

Then, only one parameter, *priority_order* (instead of: skip, only_use, lower_priority, higher_priority), should be sent to the worker/activation thread. This way even the `ModeCurationOpts` class can be removed. The Mode should probably have some basic validation for the priority_order argument, so there is some `check_priority_order(priority_order)` call before passing it further, but it still can be a simple `List[str | Set[str]]`. And could be that now the syntax could be

```python
def running(skip, only_use, priority_order, ...) -> Mode:
```

Selecting the methods for the mode at the start (filtering based on skip/use_only)  means that the ActivationResult will not know anything about the methods which we filtered out by the user. But I think that should be the way, as if the user asks not to use some methods, why to report a result for them, then? 

### proposed changes

- Replace ModeCurationOpts with priority_order dictionary.
- Add validation for priority_order
- Add mode attribute for each Method. 
- Make it possible to get methods by a Mode

**Comment by fohrloop** [comment]
### About priority_order:
- The type is: `list[set[str] | str]`
- The values are either Method names or asterisk (*)

### Needed functions:

1) In the start (main thread): validate_priority_order
- signature: validate_priority_order(priority_order, methods)
- Checks that all methods in the priority order, including asterisk, occur only once
- Checks that all method names have an existing Method in methods

2) When activating: prioritize_methods
- prioritized_methods: List[MethodCls] = prioritize_methods(methods, priority_order)
- Gets a list of prioritized methods using priority_order.
- There might be some others ways to prioritize, like platform support? Not included here.

**Comment by fohrloop** [comment]
This ticket starts to be close to completion. Next: the names for the parameters in the public API could be better.

### Selecting just some methods to be used (whitelisting) 

Instead of

```python
with keep.running(only_use=['somemethod']):
    ...
```

perhaps


```python
with keep.running(methods=['somemethod']):
    ...
```

### Selecting some methods to not to be used (blacklisting) 

Instead of 

```python
with keep.running(skip=['somemethod']):
    ...
```

perhaps

```python

with keep.running(omit_methods=['somemethod']):
    ...

with keep.running(omit_methods=['somemethod']):
    ...

# or 

with keep.running(omitted_methods=['somemethod']):
    ...

# or 

with keep.running(disabled_methods=['somemethod']):
    ...
```

**Comment by fohrloop** [comment]
This ticket starts to be close to completion. Next: the names for the parameters in the public API could be better.

### Selecting just some methods to be used (whitelisting) 

Instead of

```python
with keep.running(only_use=['somemethod']):
    ...
```

perhaps


```python
with keep.running(methods=['somemethod']):
    ...
```

### Selecting some methods to not to be used (blacklisting) 

Instead of 

```python
with keep.running(skip=['somemethod']):
    ...
```

perhaps

```python

with keep.running(omit=['somemethod']):
    ...
```

### Selecting method priority order 

Instead of 

```python
with keep.running(priority_order=['*', {'SomeMethod', 'other-method'}]):
    ...
```

perhaps

```python
with keep.running(methods_priority=['*', {'SomeMethod', 'other-method'}]):
    ...
```

**Comment by fohrloop** [comment]
This is now completed.
